server:
  port: 8080
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: "debug"
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
  jpa:
    hibernate:
      ddl-auto: "none"
---
spring:
  config:
    activate:
      on-profile: "desarrollo"
  datasource:
    url: "jdbc:mysql://localhost:3306/reuniones"
    username: root
    password: admin
    driver-class-name: "com.mysql.cj.jdbc.Driver"

server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: "pruebas"
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: "produccion"
server:
  port: 9000
